-- Insert Ingredients 
INSERT INTO ingredient (name, measurement) VALUES
('flour', 'cup'),
('sugar', 'cup'),
('brown sugar', 'cup'),
('powdered sugar', 'cup'),
('baking powder', 'teaspoon'),
('baking soda', 'teaspoon'),
('salt', 'teaspoon'),
('black pepper', 'teaspoon'),
('olive oil', 'tablespoon'),
('vegetable oil', 'tablespoon'),
('butter', 'tablespoon'),
('milk', 'cup'),
('heavy cream', 'cup'),
('egg', null),
('vanilla extract', 'teaspoon'),
('honey', 'tablespoon'),
('maple syrup', 'tablespoon'),
('peanut butter', 'tablespoon'),
('yeast', 'teaspoon'),
('cocoa powder', 'tablespoon'),
('chocolate chips', 'cup'),
('oats', 'cup'),
('rice', 'cup'),
('pasta', 'cup'),
('bread crumbs', 'cup'),
('cheese', 'cup'),
('grated parmesan', 'tablespoon'),
('tomato paste', 'tablespoon'),
('canned tomatoes', 'cup'),
('onion', null),
('garlic', 'cloves'),
('bell pepper', 'whole'),
('carrot', null),
('potato', null),
('spinach', 'cup'),
('mushrooms', 'cup'),
('chicken breast', null),
('ground beef', 'Ib'),
('bacon', 'slices'),
('sausage', 'Ib'),
('salt', 'teaspoon'),
('sugar', 'teaspoon'),
('soy sauce', 'tablespoon'),
('worcestershire sauce', 'teaspoon'),
('lemon juice', 'tablespoon'),
('lime juice', 'tablespoon');